name: Vue CI/CD

on:
  push:
    branches:
      - master  # 当 push 到 master 分支时触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9
          cache: 'npm'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 运行构建
      - name: Build project
        run: pnpm run build

      # 5. 将构建的 dist 目录上传到云服务器
      - name: Deploy to cloud server
        uses: appleboy/ssh-action@v0.1.7  # 使用 SSH Action 连接到服务器
        with:
          host: ${{ secrets.SSH_HOST }}  # SSH 服务器地址
          username: ${{ secrets.SSH_USERNAME }}  # SSH 用户名
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH 密钥（确保将私钥添加到 GitHub Secrets）
          port: 22  # 根据你的服务器配置调整端口，默认是 22
          passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}  # GitHub Secrets 中存储的密码短语
          script: |
            TARGET_PATH="/echo/echo_blog"  # 从 GitHub Secrets 获取目标路径，but，获取到是***
            echo "Deploying to ${TARGET_PATH}..."
            
            # 打印当前工作目录
            echo "Current working directory:"
            pwd
          
            # 列出当前目录中的文件
            echo "Listing files in current directory:"
            ls -l
            
            # 在远程服务器上执行的脚本
            rm -rf ${TARGET_PATH}/dist  # 删除目标路径中的旧 dist
            mkdir -p ${TARGET_PATH}/dist  # 创建新的 dist 目录
            
            cp -r ./dist ${TARGET_PATH}/  # 上传新的 dist 文件
