name: Vue CI/CD

on:
  push:
    branches:
      - master  # 当 push 到 master 分支时触发工作流

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9
          cache: 'npm'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 运行构建
      - name: Build project
        run: pnpm run build

      # 4.1 打印当前工作路径
      - name: Show work path
        run: pwd

      # 4.1 打印当前工作路径
      - name: Show work dir
        run: ls -l


      # 上传打包资源
      - name: Deploy
        uses: easingthemes/ssh-deploy@v5.1.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: '-avz'
          SOURCE: 'dist/'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: ${{ secrets.TARGET_PATH }} # 服务器目标路径